spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_EMAIL}# gmail email
    password:  ${GMAIL_PASSWORD} # gmail password
    properties:
      mail:
        smtp:
          starttls:
            enable: true